[pyprland]
plugins = ["scratchpads"]
[scratchpads.alaquake]
animation = "fromTop"
command = "kitty --class alaquake -e tmuxinator start dropdown"
class = "alaquake"
size = "1280px 720px"
lazy = true
unfocus = "hide"
force_monitor = "DP-1"
