[pyprland]
plugins = ["scratchpads"]
[scratchpads.alaquake]
animation = "fromTop"
command = "kitty --config ~/.config/kitty/kitty_quake.conf --class alaquake"
class = "alaquake"
size = "1280px 720px"
lazy = true
unfocus = "hide"

