#
#  ███╗   ███╗ ██████╗ ███╗   ██╗██╗████████╗ ██████╗ ██████╗ ███████╗
#  ████╗ ████║██╔═══██╗████╗  ██║██║╚══██╔══╝██╔═══██╗██╔══██╗██╔════╝
#  ██╔████╔██║██║   ██║██╔██╗ ██║██║   ██║   ██║   ██║██████╔╝███████╗
#  ██║╚██╔╝██║██║   ██║██║╚██╗██║██║   ██║   ██║   ██║██╔══██╗╚════██║
#  ██║ ╚═╝ ██║╚██████╔╝██║ ╚████║██║   ██║   ╚██████╔╝██║  ██║███████║
#  ╚═╝     ╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝   ╚═╝    ╚═════╝ ╚═╝  ╚═╝╚══════╝
#  
monitor = DP-1, 3840x2160@144, auto, 1, vrr, 2
#monitor = DP-2, 1920x1080@60, auto, 1, mirror, DP-1
monitor = DP-2, disable
monitor = DP-3, disable
# monitor = DP-2, 1920x1080, 0x0, 1
# monitor = DP-3, 1920x1080, 0x1080, 1
# monitor = HDMI-A-1, 3840x2160@144, auto, 1, mirror, DP-1
monitor = HDMI-A-1, disable
# monitor = DP-1, disable
